#ifndef _COMMON_H_
#define _COMMON_H_
#include "SimpleDebug.h"
namespace Common
{
    enum CommandContext {DATE_TIME_RESET, DATE_TIME_RESET_WITH_DATE, DATE_TIME_INCREMENT_DATE, DATE_TIME_SET_DATE, DATE_TIME_SET_UNAVAIL};
    enum ChristmasDoors {ONE = 1, TWO, THREE, FOUR, FIVE, SIX, SEVEN, EIGHT, NINE, TEN , ELEVEN, TWELVE, THIRTEEN, FOURTEEN, FIVETEEN, SIXTEEN, SEVENTEEN,\
    EIGHTEEN, NINETEEN, TWENTY, TWENTYONE, TWENTYTWO, TWENTYTHREE, TWENTYFOUR};

}

extern SimpleDebug<50> debugLogger;

#endif // !_COMMON_H_

